#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

# Requirements:

#    Accepts 4 parameters
#        The path to the file to be transferred
#        The IP of the server we want to transfer the file to
#        The username scp connects with
#        The path to the SSH private key that scp uses
#    Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit
fi
path=$1
ip=$2
user=$3
key=$4
scp -i "$key" -o StrictHostKeyChecking=no "$path"  "$user"@"$ip":~/
 

