#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
sudo echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo service nginx restart