#!/usr/bin/env bash
# Bash to install and configure NGINX web server on a remote server
sudo apt-get install nginx -y;
sudo su;
eval "echo 'Hello World!' > /var/www/html/index.nginx-debian.html";
sudo service nginx restart;
