#!/usr/bin/env bash
# Bash to install and configure NGINX web server on a remote server
sudo su;
apt-get update;
apt-get install nginx -y;
ufw allow 'Nginx HTTP';
eval "echo Hello World! > /var/www/html/index.nginx-debian.html";
payload="       rewrite ^/redirect_me$ http://_/$1 permanent;";
sed -i "37i\ $payload" /etc/nginx/sites-available/default;
service nginx restart;

