#!/usr/bin/env bash
# Bash to install and configure NGINX web server on a remote server
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
sudo su;
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
eval "echo 'Hello World!' > /var/www/html/index.nginx-debian.html";
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart