#!/usr/bin/env bash
#Install nginx web server with redirect
sudo apt-get install nginx -y
echo "server {
    listen 80 ;
    listen [::]:80;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 /;
    }
}" > /etc/nginx/sites-available/default
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart