#!/usr/bin/env bash
#Double the number of webservers
apt-get -y update
apt-get -y install nginx
config="/etc/nginx/sites-available/default"
sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' $config
sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' $config
sed -i 's/=404/@404/g' $config
sed -i "0,/location \/ {/s/location \/ {/&\n\t\tadd_header X-Served-By '$HOSTNAME';/" $config
service nginx restart