#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 100.25.15.47:80 check\n\tserver server2 52.91.121.153:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy start