#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
apt-get update && apt-get install nginx -y
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
