#!/usr/bin/env bash
# displays numbers from 1 to 100, with fizzbuzz algo
i=1
while [ $i -le 100 ]; do
	if ((i%3==0 && i%5!=0)); then
		echo "Fizz"
	elif ((i%5==0 && i%3!=0)); then
		echo "Buzz"
	elif ((i%3==0 && i%5==0)); then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done
