#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, by the 9nth iteration, it displays an "Hi" after the "Best School"

i=1
while [ "$i" -le 10 ]; do
echo "Best School"
if (("$i" == 9)); then
echo "Hi"
fi
i=$((i+1))
done
