#!/usr/bin/env bash
# bash script to displays "Best School", the 4th to be "bad luck", the 8th to be "good luck"
i=1
while [ "$i" -le 10 ]; do
if (("$i" == 4)); then
echo "bad luck"
elif (("$i" == 8)); then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
