#!/usr/bin/env bash
# bash script to change localhost ip and Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
sed  -r -i -e '/localhost/s/^([0-9]+\.)([0-9]+\.)([0-9]+\.)([0-9]+)/127.0.0.2/' -i  -e '2 a 8.8.8.8	facebook.com ' /etc/hosts;
