#!/usr/bin/env bash
# Bash script to configure a container to run NGInX as nginx user
sed -rine  "s/^user\s+(www-data);$/\1 nginx/p" /etc/nginx/nginx.conf;
sed -rne 's/(80)/ 8080/p' /etc/nginx/sites-enabled/default;

